#cloud-config
### write_files:
###   - path: /var/lib/rancher/conf/cloud-config.yml
###     permissions: "0644"
###     owner: root
###     content: |
###       #cloud-config
###       ssh_authorized_keys:
###         ... copy all the rest here ...
#
# Hostnames are domains, where a domain is a hierarchical, dot-separated list of subdomains;
# for example, the machine "monet", in the "example" subdomain of the "com" domain would be
# represented as "monet.example.com".
#
# Each element of the hostname must be from 1 to 63 characters long and the entire hostname,
# including the dots, can be at most 253 characters long.  Valid characters for hostnames are
# ASCII(7) letters from a to z, the digits from 0 to 9, and the hyphen (-).  A hostname may
# not start with a hyphen.
#
#hostname: this.is.a.test
hostname: supervisor

write_files:
  # Script to create and initialize the virtual interface for managemnt network
  - container: network
    path: /var/lib/nxw/management-netif.sh
    permissions: "0755"
    owner: root:root
    content: |
      #!/bin/bash

      # Virtual interface for the management network
      MGTIF="management0"

      # Physical i/f the management i/f is attacced to, selected by MAC addr
      #macif=$(grep -o -E 'nxw.management.macif=\w+' /proc/cmdline | cut -d= -f2)

      # Physical i/f the management i/f is attacced to, selected by name
      netif=$(grep -o -E 'nxw.management.netif=\w+' /proc/cmdline | cut -d= -f2)

      [ -n "$netif" ] || netif="eth0"                 # default
      [ -e "/sys/class/net/$netif" ] || exit 1        # check the i/f existed

      # Create a macvlan interface used for management subnet.
      # Using bridge mode and set promisc mode on in order
      # to get frames with physical i/f MAC addr
      ip link add $MGTIF link $netif type macvlan mode bridge
      ip link set $MGTIF up
      ip link set $MGTIF promisc on

      exit 0

rancher:
  services_include:
    kernel-extras: true
  console: debian
  ssh:
    port: 10022
  network:
    dns:
      nameservers:
      - 8.8.8.8
      override: true
    pre_cmds:
    - /var/lib/nxw/management-netif.sh
    interfaces:
      eth0:
        dhcp: true
      management0:
        address: 10.254.10.100/24
  state:
    dev: LABEL=RANCHER_STATE
    wait: true
ssh_authorized_keys:
- ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDpDepVkj2vGeQFOSPKD5+zd7ScV1nRwJ3DzfvFQ0C4v44ezMAwBd5VlOajAEdl+0AU4SyoSzBWOoOU3i+obXHH2c3IxBP/7OCa+dDZIpTnyW1vUc5BHJNJIp+7jdgtpW8sxJ4jVYKzqSuc6tkdXask/gUW1/hDeKzra4tcSdKgvXtWTqMJROyDg8z5MCGPkdFmHVNBIJ52vZxe2f7eEasUGvMKCkB8a3jdLUR8nnyr9dqVby/9JyDGlAiDRDVB2mkPEhHQkDqVrZdX5zTuGUOEZmEYiTGcntmIOIgSahicE2Oc+0EEghfQMhh71JmauOexYnmfyZzsiFCwrpMXvtdH RancherOS-common-key
